#!/bin/sh

CALCDEPS_PATH=/Users/eob/bin/closure/closure/bin
JAR_PATH=/Users/eob/bin/closure
CLOSURE_PATH=/Users/eob/bin/closure
$CALCDEPS_PATH/calcdeps.py --path $CLOSURE_PATH \
                           --input src-closure/ \
                           --compiler_jar $JAR_PATH/compiler.jar \
                           --output_mode compiled \
                           > release-closure/cts-min.js

