git clone https://github.com/cts/cts.git cts
git clone https://github.com/cts/model.git cts-model
git clone https://github.com/cts/firebase-adapter.git cts-firebase-adapter
git clone https://github.com/cts/gsheet-adapter.git cts-gsheet-adapter
git clone https://github.com/cts/html-adapter.git cts-html-adapter
git clone https://github.com/cts/parser.git cts-parser
git clone https://github.com/cts/util.git cts-util
git clone https://github.com/cts/relations.git cts-relations
git clone https://github.com/cts/engine.git cts-engine
